- name: generate join token on the master
  command: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "{{ groups['masters'][0] }}"

- name: join the node to the cluster
  command: "{{ join_command.stdout_lines[0] }}"