---
- name: make sure we use the proxy
  lineinfile:
    regexp: '^proxy.*'
    line: 'proxy={{ proxy }}'
    path: /etc/ostree/remotes.d/fedora-iot.conf
  when: proxy is defined

- name: perform an ostree update
  command: 
    cmd: "rpm-ostree upgrade --unchanged-exit-77"
  failed_when: ( result.rc not in [ 0, 77 ] )
  register: result 
  changed_when: result.rc == 0 
  notify: reboot
  

  